### ISSUE TITLE
403 accessing packages.appdynamics.com

### ISSUE THREAD

**Issue by llhughes** [Appdynamics/appdynamics-cookbooks#48]
I'm getting a 403 when trying to access packages.appdynamics.com, but am able to login into downloads.appdynamics.com. Unfortunately downlaods.appdynamics.com redirects to the sso login page and requiers a session id cookie to access. Is there any other download url that can be used for the appdynamics packages site, that doesn't redirect or require cookies?

thx

Lloyd

**Comment by dkoepke** [comment]
For technical reasons, packages.appdynamics.com returns error 403 for file not found (instead of 404). It also does not have directory listings, etc. What specific URL are you trying to hit? 

To confirm that the site is accessible for you, try this: https://packages.appdynamics.com/java/4.2.1.0/JavaAgent-4.2.1.0.zip

**Comment by llhughes** [comment]
Still gives me a 403 even though I'm logged into appdynamics

**Comment by dkoepke** [comment]
Oops, sorry. I copied the wrong URL. Try these:

https://packages.appdynamics.com/machine/4.2.1.7/MachineAgent-4.2.1.7.zip
https://packages.appdynamics.com/java/4.2.1.7/AppServerAgent-4.2.1.7.zip

The 403 is not related to login or authentication. You do not need to be logged in to download files from packages.appdynamics.com. It is simply that it returns 403 instead of 404 when you ask for a nonexistent file.

**Comment by dkoepke** [comment]
Testing confirms that the above links are operational. Closing this issue.
